### ISSUE TITLE
[cljsjs/material-ui "4.0.0-0"] Working when added to :dependencies but not when it's transitive

### ISSUE THREAD

**Issue by cj-price** [cljsjs/packages#1897]
cljsjs/material-ui is working when added to the project's :dependencies but not when it's transitive. Version 3x seemed to work just fine as a transitive dependency. When I upgraded the project to 4.0.0-0 I receive this error:

```
createSvgIcon.js:12 Uncaught TypeError: react__WEBPACK_IMPORTED_MODULE_1___default.a.memo is not a function
    at createSvgIcon (createSvgIcon.js:12)
    at eval (MoreHoriz.js:11)
    at Module../node_modules/@material-ui/core/esm/internal/svg-icons/MoreHoriz.js (material-ui.inc.js:3770)
    at __webpack_require__ (material-ui.inc.js:20)
    at eval (BreadcrumbCollapsed.js:12)
    at Module../node_modules/@material-ui/core/esm/Breadcrumbs/BreadcrumbCollapsed.js (material-ui.inc.js:626)
    at __webpack_require__ (material-ui.inc.js:20)
    at eval (Breadcrumbs.js:19)
    at Module../node_modules/@material-ui/core/esm/Breadcrumbs/Breadcrumbs.js (material-ui.inc.js:650)
    at __webpack_require__ (material-ui.inc.js:20)
    at eval (index.js:2)
    at Module../node_modules/@material-ui/core/esm/Breadcrumbs/index.js (material-ui.inc.js:662)
    at __webpack_require__ (material-ui.inc.js:20)
    at eval (index.js:40)
    at Module../node_modules/@material-ui/core/esm/index.js (material-ui.inc.js:3626)
    at __webpack_require__ (material-ui.inc.js:20)
    at eval (main.js:2)
    at eval (main.js:5)
    at Object../main.js (material-ui.inc.js:96)
    at __webpack_require__ (material-ui.inc.js:20)
    at material-ui.inc.js:84
    at material-ui.inc.js:87
```

**Comment by 2knu** [comment]
Looks like you don't have the required react and react-dom version (16.8.3 or higher). Here https://github.com/cljsjs/packages/pull/1896 it was the same issue.

Fixed here for reagent material-ui example: https://github.com/reagent-project/reagent/pull/432
